fix: 添加项目依赖锁文件，修复github工作流

diff --git a/.github/workflows/vite.yml b/.github/workflows/vite.yml
--- a/.github/workflows/vite.yml
+++ b/.github/workflows/vite.yml
@@ -45,11 +45,8 @@ jobs:
             echo "command=ci" >> $GITHUB_OUTPUT
             exit 0
           else
-            # echo "Unable to determine packager manager"
-            # exit 1
-            echo "manager=pnpm" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            exit 0
+            echo "Unable to determine packager manager"
+            exit 1
           fi
       - name: Install pnpm
         run: npm install -g pnpm
